-- Создаем таблицу users с добавленным полем phone_number
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       phone_number TEXT UNIQUE, -- Добавленное поле для номера телефона, должно быть уникальным
                       password_hash TEXT NOT NULL,
                       refresh_token TEXT,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


