-- Создаем таблицу users с добавленным полем phone_number и role
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       phone_number TEXT UNIQUE, -- Уникальный номер телефона
                       password_hash TEXT NOT NULL, -- Хэш пароля
                       refresh_token TEXT, -- Токен обновления (если используется)
                       role TEXT NOT NULL DEFAULT 'user', -- Добавленное поле для роли (по умолчанию 'user')
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Дата создания пользователя
);



