-- Создаем таблицу users с добавленным полем phone_number и role
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       phone_number TEXT UNIQUE, -- Уникальный номер телефона
                       password_hash TEXT NOT NULL, -- Хэш пароля
                       refresh_token TEXT, -- Токен обновления (если используется)
                       role TEXT NOT NULL DEFAULT 'user', -- Добавленное поле для роли (по умолчанию 'user')
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Дата создания пользователя
);

-- Создание таблицы products
CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Уникальный идентификатор
                          name TEXT NOT NULL, -- Название товара
                          img_src TEXT NOT NULL, -- Путь до главного изображения
                          description TEXT, -- Описание товара
                          price DECIMAL(10, 2) NOT NULL CHECK (price >= 0), -- Цена (до 10 цифр, 2 после запятой, неотрицательное значение)
                          characteristics JSONB NOT NULL DEFAULT '{}', -- Характеристики товара в формате JSONB
                          imgs_src JSONB NOT NULL DEFAULT '[]', -- Дополнительные изображения (список путей)
                          in_basket BOOLEAN NOT NULL DEFAULT FALSE, -- Флаг, находится ли товар в корзине
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Дата создания товара
);
